version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eventify-postgres
    environment:
      POSTGRES_DB: eventify
      POSTGRES_USER: eventify_user
      POSTGRES_PASSWORD: eventify_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
