version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: eventify-postgres-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-eventify}
      POSTGRES_USER: ${POSTGRES_USER:-eventify_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eventify_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-eventify_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: eventify-app
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-eventify_user}:${POSTGRES_PASSWORD:-eventify_password}@postgres:5432/${POSTGRES_DB:-eventify}?schema=public
      - FRONTEND_URL=http://localhost:3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-eventify_user}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
